# EasySOA build settings
#########################


# prereqs (adjust it as needed, after copying parts to $HOME/.buildr/settings.yaml)

nuxeo:
  path: 
  # to use for packaging. By default $HOME/nuxeo-dm-5.4.1-tomcat
  # specify the path either absolute or relative to the buildfile.

# release configuration

release:
  version: 2.0-SNAPSHOT

model:
  version: 0.1.2-SNAPSHOT

paf:
  version: 1.0-SNAPSHOT
