# EasySOA build settings
#########################


# prereqs (adjust it as needed, after copying parts to $HOME/.buildr/settings.yaml)

nuxeo:
  path: # to use for packaging. By default $HOME/nuxeo-dm-5.4.1-tomcat


# release configuration

release:
  version: 1.0-SNAPSHOT

model:
  version: 0.1.2-SNAPSHOT

paf:
  version: 1.0-SNAPSHOT
