# EasySOA build settings
#########################

# HOWTO
# - Copy this file or parts of this file to $HOME/.buildr/settings.yaml
# - Edit the settings at will (make sure Nuxeo and Node paths lead to a correct location)
# - Type "buildr help" from this folder to see what build commands you can use

nuxeo:
  path: 
  # to use for packaging. By default $HOME/nuxeo-dm-5.4.1-tomcat
  # specify the path either absolute or relative to the buildfile.
  
node:
  path:
  # to use for packaging. By default $HOME/node
  # specify the path either absolute or relative to the buildfile.
  
frascati:
  path: 
  # to use for packaging. By default ./frascati
  # specify the path either absolute or relative to the buildfile.
  # If not found FraSCAti 1.4 is downloaded (internet connection required).

# release configuration

release:
  version: '0.2-SNAPSHOT'

model:
  version: '0.1.2-SNAPSHOT'

paf:
  version: '1.0-SNAPSHOT'
